package com.bol.mancala.model;

public enum PitPlace {
    PLAYER_ONE_PIT_A, PLAYER_ONE_PIT_B, PLAYER_ONE_PIT_C, PLAYER_ONE_PIT_D, PLAYER_ONE_PIT_E, PLAYER_ONE_PIT_F,
    PLAYER_ONE_PIT_BIG,
    PLAYER_TWO_PIT_U, PLAYER_TWO_PIT_V, PLAYER_TWO_PIT_W, PLAYER_TWO_PIT_X, PLAYER_TWO_PIT_Y, PLAYER_TWO_PIT_Z,
    PLAYER_TWO_PIT_BIG
}
